security:
  # Configure password hashing
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # Configure user provider
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # Configure firewalls
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider

      form_login:
        login_path: app_connexion
        check_path: app_login_check
        csrf_token_id: authenticate # Utilisez csrf_token_id au lieu de csrf_token_generator
        username_parameter: email
        password_parameter: password
        default_target_path: app_home

      logout:
        path: app_logout
        csrf_token_id: logout # Option pour logout si vous utilisez CSRF

  # Configure access control
  access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }

  # Optional settings for role hierarchy
  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
